%% Combine fringe spacing data from different experiments
% load mat files generated by main_shockfringe.m from various experiments
%

path_data='C:\Users\HE BEC\Documents\lab\shockwave\summary\data';
fname_regexp='run_*.mat';
mlist=dir(fullfile(path_data,fname_regexp));
mlist={mlist.name};
Nexp=length(mlist);     % number of datasets


%% load data
S=cell(Nexp,1);     % S is cell array of structs
for ii=1:Nexp
    % load vars:
        % MAX_PEAK_N, Nal, AL_N_SD PEAK_DIFF_ALL, PEAK_DIFF_SD, N0
    varsummary={'MAX_PEAK_N', 'Nal', 'AL_N_SD', 'PEAK_DIFF_ALL', 'PEAK_DIFF_SD', 'N0'};
    S{ii}=load(fullfile(path_data,mlist{ii}),varsummary{:});
end
% tidy structure
S=cell2mat(S);      % S is now struct array

%% initialise
Npeakmax=max([S.MAX_PEAK_N]);

% plot
cc=distinguishable_colors(Npeakmax);
mm={'o','s','^','x','.','*','+','d','v','>','<','p','h'};

Ndpeakplot=2;    % number of fringe spacings to plot

%% plot - fringe spacing vs Nal
hfig_dpeak_vs_Npal=figure();

namearray={'LineWidth','MarkerFaceColor'};      % error bar graphics properties
valarray={linewidth,'w'};                 % 90 deg (normal) data

for ii=1:Nexp
    thisS=S(ii);
    ndpeak=(thisS.MAX_PEAK_N-1);
    if Ndpeakplot<ndpeak
        ndpeak=Ndpeakplot;
    end
%     p=zeros(1,ndpeak);
    for jj=1:ndpeak
        hold on;
        hdata_pal_n=ploterr(thisS.Nal,thisS.PEAK_DIFF_ALL(:,jj),thisS.AL_N_SD,thisS.PEAK_DIFF_SD(:,jj),mm{ii},'hhxy',0);
        set(hdata_pal_n(1),namearray,valarray,'Color',cc(jj,:),'MarkerSize',6,'DisplayName',sprintf('%d',jj));
        set(hdata_pal_n(2),namearray,valarray,'Color',cc(jj,:),'DisplayName','');
        set(hdata_pal_n(3),namearray,valarray,'Color',cc(jj,:),'DisplayName','');
%         p(jj)=hdata_pal_n(1);
    end
end
box on;
% lgd=legend(p);
% title(lgd,'Fringe spacing');
xlabel('$N_{AL}$');
ylabel('Fringe spacing [mm]');